backend:
  name: github
  branch: main
  repo: hayoun-k/cmstest
  site_domain: https://cmstest-dnh.pages.dev/
  base_url: https://cmstest-dnh.pages.dev/
  auth_endpoint: /api/auth

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishedAt", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      # - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Difficulty", name: "difficulty", widget: "select", options: ["Easy", "Medium", "Hard"] }
      - { label: "Cooking Time", name: "cooking_time", widget: "string" }
      - { label: "Ingredients", name: "ingredients", widget: "list", field: { label: "Ingredient", name: "ingredient", widget: "string" } }
      - { label: "Instructions", name: "instructions", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }